<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo $this->page_title; ?></title>

        <!-- Bootstrap core CSS -->
        <link href="<?php printAppUrl(); ?>/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="<?php printAppUrl(); ?>/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Custom styles for this template -->
        <link href="<?php printAppUrl(); ?>/assets/css/freelancer.min.css" rel="stylesheet">

    </head>

    <body class="index" id="page-top">

        <!-- Navigation -->
        <?php
        printTemplatePart("template-parts/navigation");
        ?>

        <!--Main Content Starts-->
        {{content}}
        <!--Main Content Ends-->

        <!-- Footer -->
        <?php
        printTemplatePart("template-parts/footer");
        ?>
    </body>

</html>