<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <?php if (printInjectedTemplates("head_title_meta_tags")) { ?>

    <?php
    } else {  ?>
        <title>
            <?php if (isset($page_title)) {
                echo $page_title . " - " . config('app_title');
            } else {
                echo config('app_title');
            }  ?>
        </title>
    <?php } ?>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="<?php echo printAssetsUrl() ?>/frontend/assets/css/styles.css" rel="stylesheet" />

    <?php
    printInjectedTemplates("before_head_ends");
    ?>

</head>

<body>
    <!-- Header-->
    <?php printTemplatePart("template-parts/header"); ?>
    <!--Main Content Starts-->
    {{content}}
    <!--Main Content Ends-->

    <!-- Footer-->
    <?php printTemplatePart("template-parts/footer"); ?>


    <?php
    printInjectedTemplates("before_body_ends");
    ?>

</body>

</html>