<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="<?php printAppUrl(); ?>/backend/assets/index2.html" class="h1"><b>Bharat</b>PHP</a>
        </div>
        <div class="card-body">



            <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.

            </p>



            <form data-gck="<?php echo config('google_recapthca_v3.sitekey'); ?>"
                action="<?php echo routeNameToURL('do_login') ?>" method="post" id="login-form" class="validation-form">
                <input type="hidden" disabled autocomplete="off" id="auth_2fa_secret" name="auth_2fa_secret"
                    class="form-control" placeholder="">
                <div id="messages" class="mb-12">


                    <!-- <div class="alert alert-warning alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>Something went wrong</div> -->


                </div>

              
                <div class="input-group mb-3 login-steps">
                    <input type="email" required id="email" name="email" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
             
                <div class="row">
                  
                    <!-- /.col -->
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

        

            <p class="mt-3 mb-1">
                <a href="<?php echo routeNameToURL('show_forgot_password_page') ?>">I forgot my password</a>
            </p>
            <p class="mb-0">
                <a href="<?php echo routeNameToURL('show_register_page') ?>" class="text-center">Register a new
                    membership</a>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<?php
injectTemplate("before_body_ends", "auth/forgot-password/template-parts/_before_body_ends", "backend");
injectTemplate("before_head_ends", "auth/forgot-password/template-parts/_before_head_ends", "backend");
injectTemplate("head_title_meta_tags", "auth/forgot-password/template-parts/_head_title_meta_tags", "backend");
?>