<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="<?php printAppUrl(); ?>/backend/assets/index2.html" class="h1"><b>Bharat</b>PHP</a>
        </div>
        <div class="card-body">



            <p class="login-box-msg">You forgot your password? Here you can reset your password.

            </p>



            <form data-gck="<?php echo config('google_recapthca_v3.sitekey'); ?>"
                action="<?php echo routeNameToURL('do_login') ?>" method="post" id="login-form" class="validation-form">
                <input type="hidden" disabled autocomplete="off" id="auth_2fa_secret" name="auth_2fa_secret"
                    class="form-control" placeholder="">
                <div id="messages" class="mb-12">


                    <!-- <div class="alert alert-warning alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>Something went wrong</div> -->


                </div>


                <div id="forgot-password-container">
                    <div class="input-group mb-3 login-steps">
                        <input type="email" required id="email" name="email" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="reset-password-container" style="display: none;">

                    <p class="mb-12"><strong>Enter the secret code which you have received in the email.</strong></p>
                    <p>



                    <div data-alert class="alertx alert-infox  radius">
                        <ul class="pd-0x">

                            <li>Password must be between 6 to 20 characters long.</li>
                            <li>Password must contain at least one uppercase.</li>
                            <li>Password must contain at least one lowercase.</li>
                            <li>Password must contain at least one digit.</li>
                            <li>Password must contain special characters from @#$%&.</li>

                        </ul>
                    </div>
                    <div class="input-group mb-3 qrcode-otp-input" style="display: nonex;">
                        <input maxlength="6" type="text" disabled id="secret" name="secret" class="form-control"
                            placeholder="Enter secret code">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3 login-steps">
                        <input type="password" id="password" disabled name="password" class="form-control"
                            placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3 login-steps">
                        <input type="password" id="passwordconfirm" disabled name="passwordconfirm" class="form-control"
                            placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                </div>



                <div class="row">

                    <!-- /.col -->
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>



            <p class="mb-1 mt-2 text-right">
                <a href="<?php echo routeNameToURL('show_login_page') ?>">Login</a>
            </p>
            <!-- <p class="mb-0">
                <a href="<?php echo routeNameToURL('show_register_page') ?>" class="text-center">Register a new
                    membership</a>
            </p> -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<?php
injectTemplate("before_body_ends", "auth/forgot-password/template-parts/_before_body_ends", "backend");
injectTemplate("before_head_ends", "auth/forgot-password/template-parts/_before_head_ends", "backend");
injectTemplate("head_title_meta_tags", "auth/forgot-password/template-parts/_head_title_meta_tags", "backend");
?>